name: build-and-publish

on:
  push:
    tags: ['v*']

permissions:
  contents: read
  id-token: write

jobs:
  build-package:
    uses: ./.github/workflows/build-package.yml
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Install NPM
        run: npm install -g npm@latest

      - name: Publish to NPM
        run: npm publish
